codango/account/fixtures/users.json
codango/account/forms.py
codango/account/migrations/0001_initial.py
codango/account/models.py
codango/account/templates/account/base.html
codango/account/templates/account/home.html
codango/account/templates/account/index.html
codango/account/tests.py
codango/account/tests/test_forms.py
codango/account/tests/test_routes.py
codango/account/tests/test_views.py
codango/account/urls.py
codango/account/views.py
codango/codango/settings.py
codango/codango/urls.py
requirements.txt

Feature sign in

---

circle.yml
codango/codango/settings/base.py

Please merge now, this should work. Changed the buildpack order on Heroku

(fixes) Changed the build pack order on heroku

---

codango/codango/wsgi.py

Reorder wsgi config file. Please merge

(fixes) Re-ordered wsgi config file

---

.gitignore
codango/account/emails.py
codango/account/templates/account/forgot-password-reset.html
codango/account/templates/account/forgot-password.html
codango/account/templates/account/index.html
codango/account/tests/test_emails.py
codango/account/tests/test_routes.py
codango/account/urls.py
codango/account/views.py
codango/codango/settings/base.py
requirements.txt

Feature email service

---

circle.yml

[Fix] added script to fix heroku deploy error

---

codango/resources/forms.py

Restricting allowed files to just PDF, DOC and DOCX

Hotfix: Allowed Files

---

circle.yml
codango/account/emails.py
codango/account/templates/account/layout/base.html
codango/codango/settings/base.py
codango/resources/tasks.py
codango/resources/templates/resources/popular-post-updates.html
codango/resources/tests/test_celery.py
codango/static/css/base.css
codango/static/js/app.js
codango/userprofile/forms.py
codango/userprofile/frequency_updates.py
codango/userprofile/migrations/0004_userprofile_frequency.py
codango/userprofile/migrations/0009_merge.py
codango/userprofile/models.py
codango/userprofile/templates/userprofile/settings.html
codango/userprofile/tests/test_routes.py
codango/userprofile/tests/test_views.py
codango/userprofile/urls.py
codango/userprofile/views.py

User can now change their password, username and set a frequency for periodic updates

Feature settings

---

README.md

Updating the README.md was necessary because as it was one would not effectively clone the repo unless they asked other Codango team members.

[Chore #112223477] Update README.md

---

.gitignore
codango/comments/migrations/0001_initial.py
codango/pairprogram/migrations/0001_initial.py
codango/resources/migrations/0001_initial.py
codango/userprofile/migrations/0001_initial.py
codango/votes/migrations/0001_initial.py

Fixes the broken Heroku app
Add migration files to the necessary applications.
A login/ register in the [app](https://codango-staging.herokuapp.com) should render the community page without an error
#120099023

#120099023 Migration on Heroku

---

codango/codango/settings/test.py
codango/middleware/navigation.py
codango/middleware/test_navigation.py

Write test for navigation middleware
The test confirm that the active tab is the one highlighted *an action handled by the middleware*.
We created a navigation middleware that fixed a bug in the nav bar sync.
#120510499

#120510499 Write tests for navigation middleware

---

README.md

It updates the README to include all Codango contributors
Add all Codango contributors to the README file.
To showcase the team behind Codango,  previous lists only had older members. It now includes everyone who has worked  and still works on Codango.

# 121392717 update readme to include all codango contributors

---

codango/codango/api.py
codango/resources/api.py
codango/resources/serializers.py
codango/resources/tests/test_api.py

Have Post and Get resource votes endpoints working on Codango REST API
Have the following endpoints working
`` GET api/v1/resources/<resource_id>/votes/ ``
`` POST api/v1/resources/<resource_id>/votes/ ``
After cloning the project, cd into codango/codango and run ` python manage.py test resources `
Endpoint: `api/v1/resources/<resource_id>/votes/`
Method: GET
Headers: Authorization (required) 
Endpoint: `api/v1/resources/<resource_id>/votes/`
Method: POST
Headers: Authorization (required) 
Parameter: vote (required) boolean
#117322335

#117322335  Build out REST Endpoints for Votes Sub-Resource

---

README.md

Updates the README
Add more detail to the README so that it's more precise to a new team member or contributor
Open the repo [here](https://github.com/andela/codango/tree/ch-readme-update-127674251) to view the README.md
The PM advised this update since in their opinion it was lacking specific information and at other instances had too much.
#127674251

#127674251 README update

---

codango/resources/views.py

It fixes the Attribute error raised on clicking on a popular resource.
Fix bug preventing viewing of a single post/ resource.
By clicking on any of the popular resources on the community page.
#126579017- Fix Internal server error on single post view page
Before 
After

#126579017 Fix Attribute error on single post view.

---

codango/community/admin.py
codango/community/models.py
codango/community/tests.py
codango/community/views.py

It creates a timestamp mixin which is inherited by all community models.
Make a timestamp mixin model to be used by other community models.
#128481605 - Create a time stamp mixin

#128481605 Create time stamp mixin

---

codango/static/css/base.css
codango/static/js/components/app.jsx
gulpfile.js
package.json

Setup home routes for React components
Setup gulp for React bundling and move the home routes to react.jsx
#128842965 - Create home for our routes component

#128842965 Create home routes component

---

codango/codango/settings/base.py
codango/community/migrations/0001_initial.py
codango/community/migrations/0002_communitymember_permission.py
codango/community/migrations/0003_auto_20160824_1103.py
codango/community/migrations/0004_auto_20160830_1041.py
codango/community/migrations/0005_auto_20160830_1052.py
codango/community/models.py
requirements.txt

It creates community-related models.
Create  and run migrations for community-related models.
Create a Codango community app that enables users to create and join groups.
128481605

#128481605  Create community  related models

---

codango/account/templates/account/partials/community-menu.html
codango/codango/urls.py
codango/community/forms.py
codango/community/models.py
codango/community/templates/community/community-create.html
codango/community/templates/community/community.html
codango/community/templates/community/partials/community_form.html
codango/community/tests.py
codango/community/tests/test_community.py
codango/community/tests/test_views.py
codango/community/urls.py
codango/community/views.py
codango/static/css/base.css
codango/static/js/app.js
codango/static/scss/base.scss

It enable users create communities on Codango
Implement a Create Community view on Codango
- Visit the review app [here](https://codango-staging-pr-151.herokuapp.com)
- Create an account and log in to get to the home page
- On the home page, click the link to create a community (+ icon) located on the community menu
- Fill in the details required and click the Create Community button. A success message will be relayed to you that your community has been created.
#129520801 -  User should be able to create a community

#129520801 -  User should be able to create a community

---

codango/static/css/base.css
codango/static/js/components/about-new.jsx
codango/static/js/components/contact-new.jsx
codango/static/js/components/menu-new.jsx
codango/static/js/tests/contact-new-test.jsx
codango/static/scss/base.scss

It adds a contact us section to the new about us page.
A react component was created for contact us, and the component was included in the new About component
- Visit the review app [here](https://codango-staging-pr-153.herokuapp.com)
- Check out the contact page on the new homepage
#128843583 - Create Contact Us Page

Create Contact Us Page

---

codango/static/js/components/contact-new.jsx

Connect the contact us form to the API.
The contact form is connected to the API, to submit the form and display the appropriate message.
- Visit the review app [here](https://codango-staging-pr-154.herokuapp.com)
- Check out the contact page on the new homepage
- Submit a message using the form
#128843603 - Connect API to the contact us page

Connect API To Contact

---

codango/static/css/base.css
codango/static/js/components/about-new.jsx
codango/static/js/components/contact-new.jsx
codango/static/js/components/footer-new.jsx
codango/static/js/tests/footer-new-test.jsx
codango/static/scss/base.scss

Create a footer for the new feature page.
- Build a footer component 
- Add the Footer component to the about us page
- Style the Footer component
- Visit the review app [here](https://codango-staging-pr-158.herokuapp.com)
- Navigate to the features page and see the footer
#130708987 - Create footer for the new feature page

Create footer for the new feature page

---

codango/static/js/components/team-directory.jsx

It updates the LinkedIn and Twitter profiles of team members on the Team page.
Fill the links pointing to twitter and LinkedIn profiles of members with the accurate information.
- Visit the review app [here](https://codango-staging-pr-155.herokuapp.com)
- Click on the "Team" link on the navigation menu.
- Roll over any of the team members and choose to visit either their LinkedIn or twitter accounts.
#128843583 - Update team page with accurate information

Update team information

---

codango/static/css/base.css
codango/static/js/components/LoginForm.jsx
codango/static/js/components/LoginModal.jsx
codango/static/js/components/RegisterForm.jsx
codango/static/js/components/menu-new.jsx
codango/static/js/components/slider.jsx
codango/static/js/tests/LoginForm-test.jsx
codango/static/js/tests/RegisterForm-test.jsx
codango/static/scss/base.scss

Add Login/Sign Up functionality to the new homepage
- Build Login Modal
- Create a login button in Nav
- Create a Login form
- Create a Sign Up form.
- Add Facebook/GooglePlus button for social authentication
- Visit the review app [here](https://codango-staging-pr-160.herokuapp.com)
- Click on the Login/Sign up on the navigation menu, then Sign Up and Login
#128843819 - Add the login functionality to the home page

Login/Sign Up Functionality for new homepage

---

codango/static/css/base.css
codango/static/js/components/Feeds.jsx
codango/static/js/components/LoginForm.jsx
codango/static/js/components/LoginModal.jsx
codango/static/js/components/Post.jsx
codango/static/js/components/RegisterForm.jsx
codango/static/js/components/SubMenu.jsx
codango/static/js/components/about-new.jsx
codango/static/js/components/home-new.jsx
codango/static/js/components/menu-new.jsx
codango/static/js/components/slider.jsx
codango/static/js/tests/LoginForm-test.jsx
codango/static/js/tests/RegisterForm-test.jsx
codango/static/scss/base.scss
package.json

Create Post feed on home page with a search bar in a submenu
- Create feeds section in the home component
- Create Popular section
- Create a search bar
- Visit the review app [here](https://codango-staging-pr-162.herokuapp.com)
- Click on the "new" navigation menu to see the home page
128843949 - Create the home page listing section with search functionality.
Feeds flow under the Submenu

Create Post feed on home page

---

codango/account/templates/account/partials/feeds.html
codango/community/templates/community/community.html
codango/community/templates/community/partials/community_list.html
codango/community/urls.py
codango/community/views.py
codango/resources/migrations/0003_resource_community.py
codango/resources/models.py
codango/resources/tests/test_routes.py
codango/resources/urls.py
codango/resources/views.py

It tie resources posted in a community to that community.
Ensure Posts & Resources posted in communities are tied to communities
* Visit the review app [here](http://codango-staging-pr-163.herokuapp.com/)
* Create an account and login with your username and password
* Create a new community. You should be redirected to the community page.
* While on the community page, create a new resource using the Share button. The newly created resource would be displayed in the community
#131067449 - Posts & Resources posted in communities are tied to communities
Visit

#131067449 - Tie posts/resources to community 

---

codango/account/tests/factories.py
codango/comments/tests/factories.py
codango/community/tests/factories.py
codango/community/tests/test_community.py
codango/pairprogram/tests/factories.py
codango/resources/tests/factories.py
codango/resources/tests/test_routes.py
codango/userprofile/tests/factories.py
codango/votes/tests/factories.py
requirements.txt

It creates factories for the models in all codango apps.
Create factory boy stubs for the models that will be used to refactor tests.
Test the functionality
`python manage.py test community.tests.factories`
#129920635 - Integrate Factory Boy

#129920635 Ft Integrate factory boy

---

codango/comments/tests/factories.py
codango/comments/tests/test_models.py
codango/comments/tests/test_views.py
codango/community/tests/factories.py
codango/community/tests/test_community.py
codango/community/tests/test_models.py
codango/community/tests/test_views.py
codango/resources/tests/factories.py
codango/resources/tests/test_api.py
codango/resources/tests/test_models.py
codango/resources/tests/test_routes.py
codango/votes/tests/factories.py
codango/votes/tests/test_models.py
requirements.txt

Create factories for models (Comments, Community, Resources, Votes) and refactor the models tests.
Create factories for models and refactor the affected tests
Clone the branch `git clone https://github.com/andela/codango.git`
Install the requirements `pip install requirements.txt`
Navigate into the directory `cd codango`
Run the  tests `python manage.py test`
#132569383 - Create factories for models (1/2)

#132569383 Ft create factories for half of the models 
